### ISSUE TITLE
Update to match example in Electron Menu documentation

### ISSUE THREAD

**Issue by nfriend** [carter-thaxton/electron-default-menu#3]
The [example menu shown on the Electron Menu documentation](https://github.com/electron/electron/blob/master/docs/api/menu.md) has several items that aren't included in this module, for example, "Paste and Match Style" and "Zoom In"/"Zoom Out".

If these omissions are intentional feel free to close this issue.

**Comment by carter-thaxton** [comment]
Yeah, that's intentional.  Those aren't usually part of most programs, unlike the menu items included here.  The code was simply based on the Electron Menu documentation.  Of course, you can always add those manually if it makes sense for your app.  Thanks!

**Comment by tzachshabtay** [comment]
Simple code for adding zoom to your menu:

```js
const menu = defaultMenu(app, shell)
const viewMenu = menu[2]
  viewMenu.submenu = viewMenu.submenu.concat([
    { type: 'separator' },
    { role: 'zoomin' },
    { role: 'zoomout' },
  ])
Menu.setApplicationMenu(Menu.buildFromTemplate(menu))
```
